{% set name = "protobuf" %}
{% set version = "4.25.8" %}

package:
  name: {{ name|lower() }}
  version: "{{ version }}"

source:
  # Use the PyPI source sdist — conda-forge maintainers may prefer fetching from
  # the official GitHub releases instead; update accordingly when opening a PR.
  url: https://files.pythonhosted.org/packages/source/p/protobuf/protobuf-{{ version }}.tar.gz
  # NOTE: Provide an exact sha256 of the sdist here before submitting the
  # recipe upstream. The placeholder has been omitted to avoid accidental
  # verification failures in local testing; contributors should fill this in
  # when creating a staged-recipes PR.

build:
  number: 0
  # We provide a build.sh script in the recipe directory. Conda-build will
  # automatically detect and run it; do not duplicate the script directive
  # here to avoid build-time confusion.

requirements:
  build:
    - {{ pin_compatible('python') }}
    - cmake
    - gcc  # needed for compiling the C-extensions
    - pip
    - setuptools
  host:
    - python
    - pip
    - libprotobuf  # prefer libprotobuf from conda-forge
  run:
    - python
    - libprotobuf

about:
  home: https://github.com/protocolbuffers/protobuf
  license: BSD-3-Clause
  summary: "Protocol Buffers — Google's data interchange format (python bindings)"

extra:
  recipe-maintainers:
    - adrasteon
