#!/usr/bin/env bash
# generate_global_env_from_manifest.sh — Generate an /etc/justnews/global.env from the canonical manifest
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
MANIFEST=${MANIFEST_OVERRIDE:-"$REPO_ROOT/infrastructure/agents_manifest.sh"}
OUT_FILE="${1:-/etc/justnews/global.env}"
BACKUP_MODE="${BACKUP_MODE:-1}"  # default: backup existing OUT_FILE
MERGE_MODE="${MERGE_MODE:-1}"    # default: merge manifest values into existing file if present
FORCE_MODE="${FORCE_MODE:-0}"    # default: do not overwrite existing values unless FORCE_MODE=1

# parse short CLI options so operators can run: 
# generate_global_env_from_manifest.sh [/outfile] [--no-backup] [--no-merge] [--force]
while [[ $# -gt 0 ]]; do
  case "$1" in
    --no-backup)
      BACKUP_MODE=0; shift;;
    --no-merge)
      MERGE_MODE=0; shift;;
    --force)
      FORCE_MODE=1; shift;;
    --out-file)
      OUT_FILE="$2"; shift 2;;
    --help|-h)
      echo "Usage: $0 [OUTFILE] [--no-backup] [--no-merge] [--force]"; exit 0;;
    *)
      # allow the first positional arg to be the outfile
      if [[ -z "$OUT_FILE" || "$OUT_FILE" = "/etc/justnews/global.env" ]]; then
        OUT_FILE="$1"; shift
      else
        shift
      fi;;
  esac
done

if [ ! -f "$MANIFEST" ]; then
  echo "Manifest $MANIFEST not found" >&2
  exit 1
fi

# Bootstrap tmp environment by sourcing manifest; manifest exports AGENTS_MANIFEST and INFRA_MANIFEST
# shellcheck disable=SC1090
. "$MANIFEST"

# Build a temporary associative map of infra services
declare -A infra_map
for e in "${INFRA_MANIFEST[@]:-}"; do
  IFS='|' read -r name desc port <<< "$e"
  infra_map["$name"]="$port"
done

# Ensure output path's directory exists
mkdir -p "$(dirname "$OUT_FILE")"

tmp_out=$(mktemp)
# Create a safe temp file and atomically write
tmp_out=$(mktemp)
declare -A existing
if [ -f "$OUT_FILE" ]; then
  # Load existing file into array
  while IFS='=' read -r k v; do
    if [[ -n "$k" ]]; then
      existing["$k"]="$v"
    fi
  done < <(grep -v '^#' "$OUT_FILE" || true)
fi

if [ "$BACKUP_MODE" = "1" ] && [ -f "$OUT_FILE" ]; then
  ts=$(date -u +%Y%m%d_%H%M%S)
  cp -v "$OUT_FILE" "$OUT_FILE.bak.$ts" || true
fi

cat > "$tmp_out" <<EOF
# Generated by generate_global_env_from_manifest.sh — do not edit by hand unless you know what you're doing
# Manifest: $MANIFEST

EOF

# Infra ports (respect existing values unless FORCE_MODE=1)
write_or_keep() {
  local key="$1"; local val="$2"
  if [ "$MERGE_MODE" = "1" ] && [ -n "${existing[$key]:-}" ] && [ "$FORCE_MODE" != "1" ]; then
    echo "$key=${existing[$key]}" >>"$tmp_out"
  else
    echo "$key=$val" >>"$tmp_out"
  fi
}

write_or_keep "GRAFANA_PORT" "${infra_map[grafana]:-3000}"
write_or_keep "PROMETHEUS_PORT" "${infra_map[prometheus]:-9090}"
write_or_keep "NODE_EXPORTER_PORT" "${infra_map[node_exporter]:-9100}"
write_or_keep "DCGM_EXPORTER_PORT" "${infra_map[dcgm_exporter]:-9400}"
write_or_keep "MARIADB_PORT" "${infra_map[mariadb]:-3306}"
write_or_keep "CHROMADB_PORT" "${infra_map[chromadb]:-3307}"
write_or_keep "CRAWL4AI_PORT" "${infra_map[crawl4ai]:-3308}"


# Derive MCP bus port from AGENTS_MANIFEST
for e in "${AGENTS_MANIFEST[@]:-}"; do
  IFS='|' read -r name module port <<< "$e"
  if [ "$name" = "mcp_bus" ]; then
    if [ -z "${existing[MCP_BUS_URL]:-}" ] || [ "$FORCE_MODE" = "1" ]; then
      echo "MCP_BUS_URL=http://localhost:$port" >>"$tmp_out"
    else
      echo "MCP_BUS_URL=${existing[MCP_BUS_URL]}" >>"$tmp_out"
    fi
  fi
done

# Add any existing MARIADB_HOST if present in environment
if [ -n "${MARIADB_HOST:-}" ]; then
  echo "MARIADB_HOST=$MARIADB_HOST" >>"$tmp_out"
fi

# Replace output file atomically, preserve mode
# Merge remaining existing keys not set in manifest output (always preserve non-conflicting existing keys)
for k in "${!existing[@]}"; do
  # Skip if we already wrote the key into tmp_out
  if ! grep -q "^$k=" "$tmp_out" 2>/dev/null; then
    echo "$k=${existing[$k]}" >>"$tmp_out"
  fi
done

mv "$tmp_out" "$OUT_FILE"
chmod 0640 "$OUT_FILE" || true
chown root:root "$OUT_FILE" || true

cat <<EOF
Wrote manifest-derived env to $OUT_FILE
EOF
